apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
  namespace: default
spec:
  tracing:
    enabled: true
    samplingRate: "1"
    stdout: false
    expandParams: true
    includeBody: true
    zipkin:
      endpointAddress: http://host.docker.internal:9411/api/v2/spans