apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: apc-configuration
spec:
  type: configuration.azure.appconfig
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: appConfiguration
      key: connectionString
  - name: subscribePollInterval
    value: 90000000000
auth:
  secretStore: apc-secret-store